version: '3'
services:
   
  node:
    build: ./packages/ui
    container_name: movie_ratings_node
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./:/app
    working_dir: /app

  postgres:
    build: ./packages/postgres
    container_name: movie_ratings_postgres
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    tty: true
    volumes:
      - ./:/app
    working_dir: /app

  redis:
    build: ./packages/redis
    container_name: movie_ratings_redis
    env_file:
      - ./.env
    ports:
      - '6379:6379'
    tty: true
    volumes:
      - ./:/app
    working_dir: /app

  rust:
    build: ./packages/server
    depends_on:
      - postgres
      - redis
    container_name: movie_ratings_rust
    env_file:
      - ./.env
    ports:
      - '4000:4000'
    tty: true
    volumes:
      - ./:/app
    working_dir: /app
