[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "./lib/lib.rs"

[[bin]]
name = "server"
path = "./server.rs"

[dependencies]
actix-session = { version = "0.6.2", features = ["cookie-session"] }
actix-web = "4"
actix-cors = "0.6"
actix-web-lab = "0.16.1"
chrono = "0.4.19"
diesel = { version = "1.4.4", features = ["chrono", "postgres", "r2d2", "uuid"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
juniper = "0.15.9"
regex = "1.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
