[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "./lib/lib.rs"

[[bin]]
name = "server"
path = "./server.rs"

[dependencies]
env_logger = "0.9.0"
serde = "1.0.137"
serde_json = "1.0.81"
actix-web = "4"
actix-cors = "0.6"
actix-web-lab = "0.16.1"
chrono = "0.4.19"
diesel = { version = "1.4.4", features = ["chrono", "postgres", "r2d2"] }
dotenv = "0.15.0"
juniper = "0.15.9"
tokio = { version = "1.19.2", features = ["full"] }
