[package]
name = "server"
version = "0.1.0"
edition = "2021"

# [lib]
# name = "lib"
# path = "./lib/lib.rs"

[[bin]]
name = "server"
path = "./server.rs"

[dependencies]
serde = "1.0.137"
serde_json = "1.0.81"
actix-web = "4"
actix-cors = "0.6"
actix-web-lab = "0.16.1"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
juniper = "0.15.9"
tokio = { version = "1.19.2", features = ["full"] }
